isTun2socksRunning bool
2dust/v2rayNG pull request #732
Opened 2020-11-08 03:41 UTC by rurirei

more status check is needed, as #728

2020-11-08 22:25 UTC, floatingrain commented on AndroidLibV2rayLite/CoreI/Status.go
> +	IsTRunning      bool
命名不应该使用“意义不明确的缩写”，这点各大编码规范中都有提及。建议
```suggestion
	IsTun2socksRunning bool
```

2020-11-08 22:26 UTC, floatingrain commented on AndroidLibV2rayLite/interact.go
> +func (v *V2RayPoint) GetIsTRunning() bool {
同样的，建议完整拼写命名

2020-11-08 22:26 UTC, floatingrain requested changes
命名问题

2020-11-09 00:52 UTC, rurirei commented on AndroidLibV2rayLite/CoreI/Status.go
> +	IsTRunning      bool
do not use variable too long.

2020-11-09 02:06 UTC, floatingrain commented on AndroidLibV2rayLite/CoreI/Status.go
> +	IsTRunning      bool
> do not use variable too long.

Maybe "IsT2SRunning" is better?

2020-11-11 04:38 UTC, yuhan6665 commented
why do we need this bool? who will call GetIsTRunning()?

2020-11-11 04:41 UTC, rurirei commented
> more status check is needed, as #728

you could do next to handle possible errors on Tun2socks start of escort.go. @yuhan6665

2020-11-11 05:19 UTC, yuhan6665 commented
> > more status check is needed, as #728
> 
> you could do next to handle possible errors on Tun2socks start of escort.go. @yuhan6665

#728 is a bit weird where looks like tun2socks error out after 10 seconds. Though I can't reproduce this issue. I think we need tun2socks log to know what happened in his device.
Even when there is an error in tun2socks, I think isTun2socksRunning will be true right?

2020-11-11 07:20 UTC, rurirei commented
> > > more status check is needed, as #728
> > 
> > 
> > you could do next to handle possible errors on Tun2socks start of escort.go. @yuhan6665
> 
> #728 is a bit weird where looks like tun2socks error out after 10 seconds. Though I can't reproduce this issue. I think we need tun2socks log to know what happened in his device.
> Even when there is an error in tun2socks, I think isTun2socksRunning will be true right?

yes you need to generate error from v.runTun2socks(), as it returns nil always.

2020-11-16 05:20 UTC, merged