优化主界面布局，删除无用布局文件，更新libv2ray的一堆奇怪错误
2dust/v2rayNG pull request #737
Opened 2020-11-08 22:08 UTC by floatingrain

为什么说是“奇怪错误”：
代码刚拉下来的时候，kt文件甚至爆红，libv2ray.aar文件中甚至没有对应函数存在。该项目应该好好考虑下自己的开源状态了，代码pull下来模块之间牛头不对马嘴，go.mod也不存在，类似一系列阻挡构建的操作严重降低他人的参与积极性。目前所有对AndroidLibV2ray的改动似乎都没有正式发布到当前代码版本中，因此我重新构建了libv2ray.aar，主分支如不接受可在后来的review中进行修改。

2020-11-09 00:51 UTC, rurirei commented
1. make sure a clean commit tree as there are no commit like "Merge branch"
2. do not upload your library as do not override official build
3. this is not a open source project with fully and completely

2020-11-09 01:05 UTC, rurirei requested changes
delete this commit as is outdated and do not provide your own build.

2020-11-09 01:17 UTC, rurirei requested changes
how deep work you are though, please clean up your pull request completely before do next commit.

2020-11-09 01:17 UTC, rurirei commented on AndroidLibV2rayLite/CoreI/Status.go
> +	return 22
no outdated commit like this please ..

2020-11-09 01:17 UTC, rurirei commented on .gitignore
> +V2rayNG/app/libs/
do not add this as we need to release official build.

2020-11-09 01:17 UTC, rurirei commented on .gitignore
> +V2rayNG/app/release/
delete this as using gradle to build app please, not this bad path from AS.

2020-11-09 01:17 UTC, rurirei commented on V2rayNG/app/src/main/res/layout/activity_main.xml
>  <android.support.v4.widget.DrawerLayout xmlns:android="http://schemas.android.com/apk/res/android"
review requested @yuhan6665

2020-11-09 02:55 UTC, floatingrain commented
> 1. make sure a clean commit tree as there are no commit like "Merge branch"
> 2. do not upload your library as do not override official build
> 3. this is not a open source project with fully and completely

1. I have no interest in this OCD but not matterd thing.
2. will fix.
3. absolutely不可理解。

2020-11-09 03:25 UTC, floatingrain commented on AndroidLibV2rayLite/CoreI/Status.go
> +	return 22
> no outdated commit like this please ..

这是什么？原仓库代码就是这样啊，我没有在此处修改。

2020-11-09 03:47 UTC, rurirei commented
> > 1. make sure a clean commit tree as there are no commit like "Merge branch"
> > 2. do not upload your library as do not override official build
> > 3. this is not a open source project with fully and completely
> 
> 1. I have no interest in this OCD but not matterd thing.
> 2. will fix.
> 3. absolutely不可理解。

we won't merge uncleared commits.

2020-11-09 03:57 UTC, rurirei commented
> > 1. make sure a clean commit tree as there are no commit like "Merge branch"
> > 2. do not upload your library as do not override official build
> > 3. this is not a open source project with fully and completely
> 
> 1. I have no interest in this OCD but not matterd thing.
> 2. will fix.
> 3. absolutely不可理解。

1. we have no interest to merge your uncleaned and uncleared commits
3. #651

2020-11-09 06:49 UTC, floatingrain commented
> > > 1. make sure a clean commit tree as there are no commit like "Merge branch"
> > > 2. do not upload your library as do not override official build
> > > 3. this is not a open source project with fully and completely
> > 
> > 1. I have no interest in this OCD but not matterd thing.
> > 2. will fix.
> > 3. absolutely不可理解。
> 
> 1. we have no interest to merge your uncleaned and uncleared commits
> 3. #651 

所有必要更正已完成，如果有权限，主界面更改可迅速合并，调整了原来大量的混乱内容，并且增大字体，增加了log的可读性。 toolbar重新与下方测试栏进行宽度匹配，以产生对称视觉效果。

2020-11-09 07:20 UTC, rurirei commented on AndroidLibV2rayLite/Process/Escort/escort.go
> -	"log"
could you try to clean this outdated commit, did you really based on latest upstream?

2020-11-09 07:20 UTC, rurirei commented on AndroidLibV2rayLite/go.mod
> +go 1.14
golang 1.15+ required

2020-11-09 07:22 UTC, rurirei commented on V2rayNG/app/src/main/kotlin/com/v2ray/ang/service/V2RayServiceManager.kt
> +                                        sinceLastQueryInSeconds)
unnecessary line wrap

2020-11-09 07:23 UTC, rurirei commented on V2rayNG/app/src/main/res/layout/activity_main.xml
> +        android:fitsSystemWindows="true">
`false` as v2rayNG do not need to overide statusBar

2020-11-09 07:26 UTC, rurirei approved these changes
how much hard work you made!

2020-11-09 07:26 UTC, rurirei commented on V2rayNG/app/src/main/kotlin/com/v2ray/ang/service/V2RayServiceManager.kt
> +                                        sinceLastQueryInSeconds)
unnecessary line wrap

2020-11-09 07:26 UTC, rurirei commented on AndroidLibV2rayLite/go.mod
> +go 1.14
golang 1.15+ required

2020-11-09 07:43 UTC, floatingrain commented
> how much hard work you made!

ALL DONE

2020-11-09 08:13 UTC, rurirei approved these changes
thanks for your hard work. review requested for big changes in UI @yuhan6665

2020-11-09 09:42 UTC, floatingrain commented
你认为怎么样 @yuhan6665 ，我让它看起来至少没那么粗糙了

2020-11-10 03:11 UTC, closed without merging

2020-11-10 03:16 UTC, rurirei commented
...

1. you can make pull request at other branch as you can do your work at your own master branch
2. make your commit tree clean as possible at your next pull request