节点按延迟排序；删除重复节点
2dust/v2rayNG pull request #847
Opened 2021-01-17 05:53 UTC by banjiaojuhao

对于节点比较多的情况还是需要这两个功能的。

2021-02-18 12:31 UTC, rurirei requested changes

2021-02-18 12:31 UTC, rurirei commented on V2rayNG/app/src/main/kotlin/com/v2ray/ang/ui/MainActivity.kt
> +        R.id.sort_all -> {
do you done a performance test, do that blocks activity?

2021-02-18 12:31 UTC, rurirei commented on V2rayNG/app/src/main/kotlin/com/v2ray/ang/viewmodel/MainViewModel.kt
> +                Int.MAX_VALUE
do warning msgs.

2021-02-18 12:31 UTC, rurirei commented on V2rayNG/app/src/main/kotlin/com/v2ray/ang/viewmodel/MainViewModel.kt
> +        AngConfigManager.storeConfigFile()
waited #865 (#701 in too.)

2021-04-01 00:01 UTC, closed without merging

2022-01-03 10:24 UTC, Animisml commented
请问有谁可以发个节点过来